export type Currency = {
  code: string;
  name: string;
  symbol: string;
};

export const currencies: Currency[] = [
  { code: "AFN", name: "AFN", symbol: "" },
  { code: "ALL", name: "ALL (Lek)", symbol: "Lek" },
  { code: "AMD", name: "AMD", symbol: "" },
  { code: "ANG", name: "ANG (ƒ)", symbol: "ƒ" },
  { code: "AOA", name: "AOA (Kz)", symbol: "Kz" },
  { code: "ARS", name: "ARS ($)", symbol: "$" },
  { code: "AUD", name: "AUD ($)", symbol: "$" },
  { code: "AWG", name: "AWG (ƒ)", symbol: "ƒ" },
  { code: "AZN", name: "AZN (ман)", symbol: "ман" },
  { code: "BAM", name: "BAM (KM)", symbol: "KM" },
  { code: "BBD", name: "BBD ($)", symbol: "$" },
  { code: "BDT", name: "BDT (Tk)", symbol: "Tk" },
  { code: "BGN", name: "BGN (лв)", symbol: "лв" },
  { code: "BHD", name: "BHD", symbol: "" },
  { code: "BIF", name: "BIF", symbol: "" },
  { code: "BMD", name: "BMD ($)", symbol: "$" },
  { code: "BND", name: "BND ($)", symbol: "$" },
  { code: "BOB", name: "BOB ($b)", symbol: "$b" },
  { code: "BOV", name: "BOV", symbol: "" },
  { code: "BRL", name: "BRL (R$)", symbol: "R$" },
  { code: "BSD", name: "BSD ($)", symbol: "$" },
  { code: "BTN", name: "BTN", symbol: "" },
  { code: "BWP", name: "BWP (P)", symbol: "P" },
  { code: "BYN", name: "BYN (Br)", symbol: "Br" },
  { code: "BZD", name: "BZD (BZ$)", symbol: "BZ$" },
  { code: "CAD", name: "CAD ($)", symbol: "$" },
  { code: "CDF", name: "CDF", symbol: "" },
  { code: "CHE", name: "CHE", symbol: "" },
  { code: "CHF", name: "CHF", symbol: "" },
  { code: "CHW", name: "CHW", symbol: "" },
  { code: "CLF", name: "CLF", symbol: "" },
  { code: "CLP", name: "CLP ($)", symbol: "$" },
  { code: "CNY", name: "CNY (¥)", symbol: "¥" },
  { code: "COU", name: "COU", symbol: "" },
  { code: "CRC", name: "CRC (₡)", symbol: "₡" },
  { code: "CUC", name: "CUC", symbol: "" },
  { code: "CUP", name: "CUP (₱)", symbol: "₱" },
  { code: "CVE", name: "CVE", symbol: "" },
  { code: "CZK", name: "CZK (Kč)", symbol: "Kč" },
  { code: "DJF", name: "DJF (CHF)", symbol: "CHF" },
  { code: "DKK", name: "DKK (kr)", symbol: "kr" },
  { code: "DOP", name: "DOP (RD$)", symbol: "RD$" },
  { code: "DZD", name: "DZD", symbol: "" },
  { code: "EGP", name: "EGP (E£)", symbol: "E£" },
  { code: "ERN", name: "ERN", symbol: "" },
  { code: "ETB", name: "ETB", symbol: "" },
  { code: "EUR", name: "EUR (€)", symbol: "€" },
  { code: "FJD", name: "FJD ($)", symbol: "$" },
  { code: "FKP", name: "FKP (£)", symbol: "£" },
  { code: "GBP", name: "GBP (£)", symbol: "£" },
  { code: "GEL", name: "GEL", symbol: "" },
  { code: "GHS", name: "GHS (GH¢)", symbol: "GH¢" },
  { code: "GIP", name: "GIP (£)", symbol: "£" },
  { code: "GMD", name: "GMD", symbol: "" },
  { code: "GNF", name: "GNF", symbol: "" },
  { code: "GTQ", name: "GTQ (Q)", symbol: "Q" },
  { code: "GYD", name: "GYD ($)", symbol: "$" },
  { code: "HKD", name: "HKD (HK$)", symbol: "HK$" },
  { code: "HNL", name: "HNL (L)", symbol: "L" },
  { code: "HRK", name: "HRK (kn)", symbol: "kn" },
  { code: "HTG", name: "HTG", symbol: "" },
  { code: "HUF", name: "HUF (Ft)", symbol: "Ft" },
  { code: "JMD", name: "JMD (J$)", symbol: "J$" },
  { code: "JOD", name: "JOD", symbol: "" },
  { code: "USD", name: "USD ($)", symbol: "$" },
];

export const currencyFormatter = (currency: string) => {
  return new Intl.NumberFormat("default", {
    style: "currency",
    currency,
    currencyDisplay: "symbol",
  });
};
